name: Build JS

on:
  #push:
    #branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'
    
    - name: Create maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [{
            "id": "trombone-mvn-repo",
            "username": "voyanttools",
            "password": "${{secrets.GITHUB_TOKEN}}"
          }]
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: unzip WAR
      run: jar -xvf target/Voyant*.war
    
    - name: Run JSCacher
      run: java -classpath "target/WEB-INF/lib/*:target/WEB-INF/classes/." org.voyanttools.voyant.JSCacher --webappPath=target/
    
    - name: Archive JS artifacts
      uses: actions/upload-artifact@v2
      with:
        name: js-files
        path: |
          target/resources/voyant/current/voyant.js
          target/resources/voyant/current/voyant.min.js
