name: Build Spyral

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Node install
        run: npm ci
        working-directory: src/main/webapp/resources/spyral
        
      - name: Build Spyral
        run: npm run-script build-spyral
        working-directory: src/main/webapp/resources/spyral
        
